--
-- PostgreSQL database dump
--

\restrict IgJxwgbHIVhCp0OPn6lJPUeiq3NZHy3LDfMmUFzKAGvzCcJkeqIuiErkjmglXrD

-- Dumped from database version 16.13
-- Dumped by pg_dump version 16.13

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA IF NOT EXISTS public;


--
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON SCHEMA public IS 'standard public schema';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auditoria; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auditoria (
    id_auditoria bigint NOT NULL,
    accion character varying(80) NOT NULL,
    detalle text,
    email_usuario character varying(150),
    entidad character varying(80) NOT NULL,
    entidad_id character varying(64),
    fecha timestamp(6) without time zone NOT NULL,
    firma_referencia character varying(500),
    id_usuario bigint,
    nombre_usuario character varying(120)
);


--
-- Name: auditoria_id_auditoria_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auditoria ALTER COLUMN id_auditoria ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auditoria_id_auditoria_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: clasificacion_manual; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.clasificacion_manual (
    id_equipo bigint NOT NULL,
    activo boolean NOT NULL,
    fecha_ultimo timestamp(6) without time zone NOT NULL,
    gc integer NOT NULL,
    gf integer NOT NULL,
    id_usuario_ultimo bigint,
    modificado_por character varying(120),
    pe integer NOT NULL,
    pg integer NOT NULL,
    pj integer NOT NULL,
    pp integer NOT NULL,
    pts integer NOT NULL,
    sello_firma character varying(500)
);


--
-- Name: equipo; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.equipo (
    id_equipo bigint NOT NULL,
    nombre character varying(120) NOT NULL,
    pais character varying(120) NOT NULL,
    grupo character varying(10) NOT NULL,
    ranking_fifa integer NOT NULL,
    bandera_url text,
    CONSTRAINT equipo_ranking_fifa_check CHECK ((ranking_fifa >= 0))
);


--
-- Name: equipo_id_equipo_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.equipo_id_equipo_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: equipo_id_equipo_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.equipo_id_equipo_seq OWNED BY public.equipo.id_equipo;


--
-- Name: evento_partido; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.evento_partido (
    id_evento bigint NOT NULL,
    id_partido bigint NOT NULL,
    tipo_evento character varying(50) NOT NULL,
    minuto integer NOT NULL,
    descripcion text,
    CONSTRAINT evento_partido_minuto_check CHECK ((minuto >= 0))
);


--
-- Name: evento_partido_id_evento_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.evento_partido_id_evento_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: evento_partido_id_evento_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.evento_partido_id_evento_seq OWNED BY public.evento_partido.id_evento;


--
-- Name: partido; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.partido (
    id_partido bigint NOT NULL,
    id_equipo_local bigint NOT NULL,
    id_equipo_visitante bigint NOT NULL,
    fecha timestamp without time zone NOT NULL,
    estadio character varying(120) NOT NULL,
    fase character varying(50) NOT NULL,
    estado character varying(30) NOT NULL,
    en_descanso boolean NOT NULL,
    inicio_en_vivo timestamp(6) without time zone,
    inicio_segundo_tiempo timestamp(6) without time zone,
    minuto_congelado integer,
    minuto_suspendido integer,
    programado_por character varying(120),
    tiempo_adicion integer NOT NULL,
    CONSTRAINT chk_partido_equipos_distintos CHECK ((id_equipo_local <> id_equipo_visitante))
);


--
-- Name: partido_id_partido_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.partido_id_partido_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: partido_id_partido_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.partido_id_partido_seq OWNED BY public.partido.id_partido;


--
-- Name: prediccion; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.prediccion (
    id_prediccion bigint NOT NULL,
    id_usuario bigint NOT NULL,
    id_partido bigint NOT NULL,
    prob_local numeric(5,4) NOT NULL,
    prob_empate numeric(5,4) NOT NULL,
    prob_visitante numeric(5,4) NOT NULL,
    explicacion text,
    nivel_confianza character varying(30),
    fecha_prediccion timestamp without time zone DEFAULT now() NOT NULL,
    goles_local_previsto integer,
    goles_visitante_previsto integer,
    modelo_version character varying(50),
    CONSTRAINT prediccion_prob_empate_check CHECK (((prob_empate >= (0)::numeric) AND (prob_empate <= (1)::numeric))),
    CONSTRAINT prediccion_prob_local_check CHECK (((prob_local >= (0)::numeric) AND (prob_local <= (1)::numeric))),
    CONSTRAINT prediccion_prob_visitante_check CHECK (((prob_visitante >= (0)::numeric) AND (prob_visitante <= (1)::numeric)))
);


--
-- Name: prediccion_id_prediccion_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.prediccion_id_prediccion_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: prediccion_id_prediccion_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.prediccion_id_prediccion_seq OWNED BY public.prediccion.id_prediccion;


--
-- Name: resultado; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.resultado (
    id_resultado bigint NOT NULL,
    id_partido bigint NOT NULL,
    goles_local integer NOT NULL,
    goles_visitante integer NOT NULL,
    fecha_registro timestamp without time zone DEFAULT now() NOT NULL,
    CONSTRAINT resultado_goles_local_check CHECK ((goles_local >= 0)),
    CONSTRAINT resultado_goles_visitante_check CHECK ((goles_visitante >= 0))
);


--
-- Name: resultado_id_resultado_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.resultado_id_resultado_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: resultado_id_resultado_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.resultado_id_resultado_seq OWNED BY public.resultado.id_resultado;


--
-- Name: usuario; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.usuario (
    id_usuario bigint NOT NULL,
    nombre character varying(120) NOT NULL,
    email character varying(150) NOT NULL,
    password character varying(255) NOT NULL,
    rol character varying(50) NOT NULL,
    fecha_registro timestamp without time zone DEFAULT now() NOT NULL,
    fecha_modificacion timestamp(6) without time zone,
    modificado_por character varying(120),
    CONSTRAINT usuario_rol_check CHECK (((rol)::text = ANY ((ARRAY['ADMIN'::character varying, 'USER'::character varying])::text[])))
);


--
-- Name: usuario_id_usuario_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.usuario_id_usuario_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: usuario_id_usuario_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.usuario_id_usuario_seq OWNED BY public.usuario.id_usuario;


--
-- Name: equipo id_equipo; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.equipo ALTER COLUMN id_equipo SET DEFAULT nextval('public.equipo_id_equipo_seq'::regclass);


--
-- Name: evento_partido id_evento; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.evento_partido ALTER COLUMN id_evento SET DEFAULT nextval('public.evento_partido_id_evento_seq'::regclass);


--
-- Name: partido id_partido; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.partido ALTER COLUMN id_partido SET DEFAULT nextval('public.partido_id_partido_seq'::regclass);


--
-- Name: prediccion id_prediccion; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.prediccion ALTER COLUMN id_prediccion SET DEFAULT nextval('public.prediccion_id_prediccion_seq'::regclass);


--
-- Name: resultado id_resultado; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.resultado ALTER COLUMN id_resultado SET DEFAULT nextval('public.resultado_id_resultado_seq'::regclass);


--
-- Name: usuario id_usuario; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuario ALTER COLUMN id_usuario SET DEFAULT nextval('public.usuario_id_usuario_seq'::regclass);


--
-- Name: auditoria auditoria_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auditoria
    ADD CONSTRAINT auditoria_pkey PRIMARY KEY (id_auditoria);


--
-- Name: clasificacion_manual clasificacion_manual_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.clasificacion_manual
    ADD CONSTRAINT clasificacion_manual_pkey PRIMARY KEY (id_equipo);


--
-- Name: equipo equipo_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.equipo
    ADD CONSTRAINT equipo_pkey PRIMARY KEY (id_equipo);


--
-- Name: evento_partido evento_partido_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.evento_partido
    ADD CONSTRAINT evento_partido_pkey PRIMARY KEY (id_evento);


--
-- Name: partido partido_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.partido
    ADD CONSTRAINT partido_pkey PRIMARY KEY (id_partido);


--
-- Name: prediccion prediccion_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.prediccion
    ADD CONSTRAINT prediccion_pkey PRIMARY KEY (id_prediccion);


--
-- Name: resultado resultado_id_partido_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.resultado
    ADD CONSTRAINT resultado_id_partido_key UNIQUE (id_partido);


--
-- Name: resultado resultado_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.resultado
    ADD CONSTRAINT resultado_pkey PRIMARY KEY (id_resultado);


--
-- Name: usuario usuario_email_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuario
    ADD CONSTRAINT usuario_email_key UNIQUE (email);


--
-- Name: usuario usuario_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuario
    ADD CONSTRAINT usuario_pkey PRIMARY KEY (id_usuario);


--
-- Name: idx_evento_partido_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_evento_partido_id ON public.evento_partido USING btree (id_partido);


--
-- Name: idx_partido_fecha; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_partido_fecha ON public.partido USING btree (fecha);


--
-- Name: idx_prediccion_partido_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_prediccion_partido_id ON public.prediccion USING btree (id_partido);


--
-- Name: idx_prediccion_usuario_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_prediccion_usuario_id ON public.prediccion USING btree (id_usuario);


--
-- Name: evento_partido fk_evento_partido; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.evento_partido
    ADD CONSTRAINT fk_evento_partido FOREIGN KEY (id_partido) REFERENCES public.partido(id_partido) ON DELETE CASCADE;


--
-- Name: partido fk_partido_equipo_local; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.partido
    ADD CONSTRAINT fk_partido_equipo_local FOREIGN KEY (id_equipo_local) REFERENCES public.equipo(id_equipo);


--
-- Name: partido fk_partido_equipo_visitante; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.partido
    ADD CONSTRAINT fk_partido_equipo_visitante FOREIGN KEY (id_equipo_visitante) REFERENCES public.equipo(id_equipo);


--
-- Name: prediccion fk_prediccion_partido; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.prediccion
    ADD CONSTRAINT fk_prediccion_partido FOREIGN KEY (id_partido) REFERENCES public.partido(id_partido) ON DELETE CASCADE;


--
-- Name: prediccion fk_prediccion_usuario; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.prediccion
    ADD CONSTRAINT fk_prediccion_usuario FOREIGN KEY (id_usuario) REFERENCES public.usuario(id_usuario) ON DELETE CASCADE;


--
-- Name: resultado fk_resultado_partido; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.resultado
    ADD CONSTRAINT fk_resultado_partido FOREIGN KEY (id_partido) REFERENCES public.partido(id_partido) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

\unrestrict IgJxwgbHIVhCp0OPn6lJPUeiq3NZHy3LDfMmUFzKAGvzCcJkeqIuiErkjmglXrD

